### PR TITLE
Fix mismatch between colors and error types

### LINKED ISSUE #9: Update the code to Python 3
DETAD code is in Python 2 and might not be compatible in a straightforward way with Python 3. 

Action items:
- update the conda environment packages, such as Python, numpy, and matplotlib
- remove legacy syntax specific to only Python 2
- verify that results on the example files are not changed

### PR DESCRIPTION
**Pull request by sunniesuhyoung**
Currently there's a mismatch between colors and error types in the right "Removing Error Impact" plot.
This fix correctly matches: light blue (background), light green (double detection), blue (wrong label), red (confusion) and pink (localization).

### CODE REVIEW

**Comment by HumamAlwassel** [comment]
Hello Sunnie,

Thanks for your interest in DETAD. 

I reviewed your pull request and I verified that there's no mismatch between the colors and the error types in our code. To see that, run the validation example as detailed in the README.md. With your code changes, you will see that the largest bar (middle bar) on the right changes to dark blue (i.e. Wrong Label Error). However, there are no wrong label errors in the prediction file since there are no dark blue areas in the false-positive profile on the left. Thus, we expect no impact from removing the wrong label errors (which do not exists), and the dark blue bar should be 0.0 on the right plot.

Hope this helps clear up any confusion.

Cheers!

**Comment by sunniesuhyoung** [comment]
Hi Humam,

I'm getting different results which I suspect to be due to some differences between Python 2 and Python 3. FYI I'm running the code in Python 3 with minor changes like replacing print '...' with print('...') and iteritems() with items().

Suppose I have:
- `colors = ['#33a02c', '#b2df8a', '#1f78b4', '#fb9a99', '#e31a1c', '#a6cee3']`
- `fp_error_analysis.average_mAP_gain = {'Double Detection Err': 0.009183850927437787, 'Wrong Label Err': 0.00046761714940901644, 'Localization Err': 0.11348941344452879, 'Confusion Err': 0.00124599899578548, 'Background Err': 0.024977222253642517}`.

I get the following when I run the code:

`np.array(list(fp_error_analysis.average_mAP_gain.keys()))[order]`
[Background Err, Double Detection Err, Wrong Label Err, Confusion Err, Localization Err]

`np.array(colors[1:])[order]`
['#a6cee3', '#b2df8a', '#1f78b4', '#e31a1c', '#fb9a99'] = [light blue, light green, blue, red, pink]

`colors[::-1]`
['#a6cee3', '#e31a1c', '#fb9a99', '#1f78b4', '#b2df8a', '#33a02c'] = [light blue, red, pink, blue, light green, green]

Which is why I proposed changing `colors[::-1]` to `np.array(colors[1:])[order]`, but it seems from your reply this change is inconsistent with the error type ordering in Python 2. Thanks for looking into it!

**Comment by HumamAlwassel** [comment]
I see! I was testing the code environment we provide in the repo (which is in Python 2). Can you please test the code on your side using the conda environment?

I also opened an issue for updating the code to Python 3. I will work on it soon. 
Thanks for being this to our attention.

Cheers

**Comment by HumamAlwassel** [comment]
Hi @sunniesuhyoung,

I have upgraded the DETAD code to Python 3.
There were more issues (other than the one you pointed out) that needed fixing when switching from Python 2 to 3. So please pull the latest version. 

Thanks again for bringing this to our attention :) 

Cheers!

**Pull request closed without merging**
